# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2bcfa1e597708762d223182b50aac50eeae03c04bba4d006749a52caeac76598dc76c43803958acf710cac3a430f5f5c407f89fbbf2a63bcb8ae0214741280c

test:
  secret_key_base: ce41575f93fb5711bc82d4b6b0653d1252875b6b7b23150d98a6dd97c9dc8ef40c6cf849d250c02f8068954d2aeb582a247902e8af8b632746778d34fdb896ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
